### PR TITLE
Allow KServe to have its own local gateways for Serverless mode

### PR DESCRIPTION
**Pull request by israel-hdez**
Cherry-pick of kserve/kserve#3737

### CODE REVIEW

**Comment by Jooho** [comment]
You need to change overlay inferenceservice configmap as well.

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
@Jooho when you comment is addressed, please add lgtm label :)

**Comment by israel-hdez** [comment]
I updated the overlay.

**Pull request merged**
