### PR TITLE
[Sync] kserve/kserve-master to master branch

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
#### Motivation
This is Release Sync. Detail information is here:
- Sync Date: 20230825
- `odh/kserve` branch: master

related task : https://github.com/opendatahub-io/modelmesh-serving/issues/173

### CODE REVIEW

**Comment by israel-hdez** [comment]
@vaibhavjainwiz Can you link the ticket that this PR would be closing, or is related to?

**Comment by vaibhavjainwiz** [comment]
> @vaibhavjainwiz Can you link the ticket that this PR would be closing, or is related to?

done.. I had update the description of ticket to include related task.

**Comment by israel-hdez** [comment]
> done.. I had update the description of ticket to include related task.

Perhaps, next time, create the ticket in this repo, instead of modelmesh-serving repo... or how this would be related to ModelMesh?

**Comment by vaibhavjainwiz** [comment]
> > done.. I had update the description of ticket to include related task.
> 
> Perhaps, next time, create the ticket in this repo, instead of modelmesh-serving repo... or how this would be related to ModelMesh?

sure.. this time I just a github functionality to automatically create a GitHub issue for their sub-task so maybe it by default pick modelmesh-serving. I would take care of it going forward.

**Comment by vaibhavjainwiz** [comment]
In PR checks only openshift-ci checks are failing because of permission issue on quay.io repos. We could ignore them because GitHub Actions are already taken care of it.

**Review by israel-hdez — APPROVED** [review]

**Comment by israel-hdez** [comment]
/override ci/prow/pr-image-mirror-kserve-agent ci/prow/pr-image-mirror-kserve-controller ci/prow/pr-image-mirror-kserve-router

**Pull request merged**
