### PR TITLE
[Cherry pick] fixes to current release branch 0.11.1

### PR DESCRIPTION
**Pull request by israel-hdez**
**What this PR does / why we need it**:

Cherry pick:
- kserve/kserve#3259 - Fix python library around environment variables
- kserve/kserve#3371 - By default, mount PVC volumes directly
- kserve/kserve#3436 - Add capability to disable ingress creation in RawDeployment mode

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
@Jooho Do you want to include https://github.com/kserve/kserve/pull/3463?

**Comment by Jooho** [comment]
@terrytangyuan yes!

**Comment by spolti** [comment]
The raw deployment is not 100% working, right?
Do we want to cherry-pick it?

**Comment by terrytangyuan** [comment]
> The raw deployment is not 100% working, right?

What is not working?

**Comment by spolti** [comment]
> > The raw deployment is not 100% working, right?
> 
> What is not working?

That combination that Daniele mentioned on yesterday's meeting.
We might need to wait for the fix, no?

**Comment by israel-hdez** [comment]
> @Jooho Do you want to include [kserve#3463](https://github.com/kserve/kserve/pull/3463)?

@terrytangyuan I think that @Jooho already picked that one here: https://github.com/opendatahub-io/kserve/pull/221.

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Pull request merged**
