### PR TITLE
Update dependencies to resolve security scans

### PR DESCRIPTION
**Pull request by Xaenalt**
Dependency update to address security scans

Need to make sure bumping Ray version here is fine, should be fine if tests pass
Changed over the storage-initializer to use UBI-based images. Need to make sure tests pass with it

### CODE REVIEW

**Comment by Xaenalt** [comment]
Testing instructions should just be does this storage-initializer work, which I think the tests will cover

**Comment by israel-hdez** [comment]
Need to figure out how to make E2Es more stable.
Retesting, although I think this PR should go against `release-v0.11` branch.

/test e2e-slow e2e-fast

**Comment by israel-hdez** [comment]
Forcing to :green_circle: CI jobs with known issues

/override ci/prow/pr-image-mirror-kserve-agent ci/prow/pr-image-mirror-kserve-controller ci/prow/pr-image-mirror-kserve-router ci/prow/pr-image-mirror-kserve-storage-initializer

**Comment by israel-hdez** [comment]
Cycle PR to force GHActions to run.

/reopen

**Review by israel-hdez — APPROVED** [review]
Approving to let auto merge as soon as CI passes

**Comment by Xaenalt** [comment]
Since we're not using 3.11, and it looks like the test failure is independent, going to merge so we have security scans resolved

**Pull request merged**
