### PR TITLE
Sync

### PR DESCRIPTION
**Pull request by spolti**
master to master sync, manually done due conflicts.

### CODE REVIEW

**Comment by spolti** [comment]
There seems to be some issue on the infra:
```
Waiting for pod -l app=domain-mapping to be created
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-03-20T22:41:31Z"}
```

**Review by israel-hdez — APPROVED** [review]

**Pull request merged**
