### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by hdefazio**
Sync main branches and resolve conflicts

### CODE REVIEW

**Review by israel-hdez — COMMENTED** [review]
I ran the E2Es. I have a few failing ones related to:
* Tensorflow
* Canaraies,
* Triton

Most likely, the failures are because of my setup. For some reason, CRC is not applying properly the SCCs. Everything else is passing.

We still don't formally support such features in ODH, so I would be happy to approve.

The only too aggressive change I'm seeing is on the `python/kserve/poetry.lock` that has a major update. It is probably better to rollback that change and fix the lockfile by running `poetry lock --no-update` inside the `python/kserve` path.

**Comment by hdefazio** [comment]
@israel-hdez It started as just a merge but I did a rebase recently to fix the CI test which might be the cause. Do I need to revert it?

**Comment by israel-hdez** [comment]
@hdefazio Try re-synching without reverting. Something like:
`git merge ea2318c`

Because `ea2318c` was the last commit you synced. If it does it cleanly, you may just push another PR with such merge to re-join the history. If there are conflicts... well... evaluate if it would be easier to fix the conflicts, or if you would prefer to revert.

**Pull request merged**
