### PR TITLE
cherry-pick(#369) and fix conflict

### PR DESCRIPTION
**Pull request by Jooho**
cherry pick: https://github.com/opendatahub-io/kserve/pull/369

### CODE REVIEW

**Comment by Jooho** [comment]
Do not merge this PR until other PRs are ready.

**Comment by israel-hdez** [comment]
If this is just a cherry-pick, we should be able to merge this. Right?
IMO, it shouldn't have any unwanted effect regardless the other PRs aren't ready yet.

**Review by israel-hdez — APPROVED** [review]
Leaving my approval, in case you want to merge in advance:

/lgtm

**Review by spolti — APPROVED** [review]

**Pull request merged**
